import type { Browser, Cookie } from 'puppeteer';

/**
 * Abstract base class for cookie scrapers.
 * Extend this to add support for new platforms.
 */
export abstract class BaseScraper {
  /** Platform identifier, e.g. 'instagram', 'tiktok' */
  abstract readonly platform: string;

  /** Output file name for cookies, e.g. 'instagram.txt' */
  abstract readonly cookieFileName: string;

  /** Refresh interval in milliseconds */
  abstract readonly intervalMs: number;

  /** Required cookie names that must be present for a valid session */
  abstract readonly requiredCookies: string[];

  /**
   * Perform the login/scraping flow and return cookies.
   * The browser instance is launched and closed by the scheduler.
   */
  abstract scrape(browser: Browser): Promise<Cookie[]>;

  /**
   * Convert Puppeteer cookies to Netscape cookie file format (used by yt-dlp).
   */
  toCookieFileContent(cookies: Cookie[]): string {
    const lines: string[] = [
      '# Netscape HTTP Cookie File',
      `# Generated by cookie-getter for ${this.platform}`,
    ];

    for (const cookie of cookies) {
      const domain = cookie.domain || `.${this.platform}.com`;
      const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const path = cookie.path || '/';
      const secure = cookie.secure ? 'TRUE' : 'FALSE';
      const expires = Math.floor(cookie.expires ?? 0);
      const name = cookie.name;
      const value = cookie.value;

      lines.push(`${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}`);
    }

    return lines.join('\n') + '\n';
  }

  /**
   * Validate that required cookies are present.
   */
  validateCookies(cookies: Cookie[]): boolean {
    const names = new Set(cookies.map((c) => c.name));
    return this.requiredCookies.every((name) => names.has(name));
  }
}
